fix package installer & include in kali build

diff --git a/plugins/envsetup b/plugins/envsetup
--- a/plugins/envsetup
+++ b/plugins/envsetup
@@ -41,7 +41,7 @@ do_mount() {
 
     if ! is_mounted "$chroot_dir/dev" >>/dev/null; then
       shout "mounting: $chroot_dir/dev"
-      $SUDO mount --rbind /dev "$chroot_dir"/dev
+      $SUDO mount -o bind /dev "$chroot_dir"/dev
     fi
 
     if ! is_mounted "$chroot_dir"/proc >>/dev/null; then
@@ -316,6 +316,7 @@ setup_user()
     install_pkg "openssl"   
     run_cmd "$CMD"
     run_cmd "$pass_set_cmd"
+    touch "$ROOT_DIR"/out/"${chroot_dir}"_user_details.txt
     echo -e "$_user\n$_passwd" > "$ROOT_DIR/out/${chroot_dir}_user_details.txt"
 }
 arch_translate() {
@@ -439,7 +440,7 @@ do_tar_bzip() {
 }
 
 run_cmd() {
-    local command="$1"
+    local command="$*"
     do_chroot_ae "$chroot_dir" "$command"
 }
 
@@ -447,6 +448,6 @@ install_pkg()
 {
     pkg_name="$*"
 
-    run_cmd "export DEBIAN_FRONTEND=noninteractive && apt install -y $pkg_name" || warn "Couldn't install $pkg_name"
+    run_cmd "apt install -y $pkg_name" || warn "Couldn't install $pkg_name"
     run_cmd "apt clean"
 }
